### ISSUE TITLE
Call .cuda() on module if self.use_cuda=True

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/inferno#21]
Currently, the `module_` is not automatically moved to cuda even if `use_cuda=True`. This is unexpected and should change.

This is what @ottonemo has to say about this:

>I suppose so, yes. I was worried that it might interfere with settings that add parameters to the module after the point where we automatically apply .cuda() to the model which would result in these parameters to be excluded from the type conversion. One solution would be to do this conversion every time training starts (as is the case here) and mention in the documentation that there might be a case where the user has to call .cuda() on the model by themselves in certain cases.

>In short my suggestion is: Implement self.module_.cuda() in on_train_begin of the base class and leave a comment somewhere (where?) in a docstring.

My suggestion: When a parameter is set on `module_`, the module needs to be re-initialized using the `initialize_module` method. We could move the `.cuda()` call to the end of this method.

I have another fear, though. What if the user wants *part* of the module and data to be on cuda and part on cpu? I guess we need to make sure that as long as `use_cuda=False`, we don't

**Comment by ottonemo** [comment]
> My suggestion: When a parameter is set on module_, the module needs to be re-initialized using the initialize_module method. We could move the .cuda() call to the end of this method.

With parameter I literally meant `torch.nn.Parameter`, not a parameter in the sense of `set_params`, sorry for the confusion. Nevertheless, placing the conversion to `initialize_module` might just be OK.

> I have another fear, though. What if the user wants part of the module and data to be on cuda and part on cpu? I guess we need to make sure that as long as use_cuda=False, we don't

Since the user has potentially all control over the module it is easily possible to just manually lift specific parts of the model to the GPU and leave others on the CPU so I don't worry too much about that.

**Comment by ottonemo** [comment]
Another note: `to_var` is often called without the `use_cuda` parameter. This should be addressed in this issue as well.

**Comment by benjamin-work** [comment]
Good point. It's just stupidly hard to test for those things :/

**Comment by ottonemo** [comment]
> It's just stupidly hard to test for those things

For inputs to the model we could use a mock model and verify that the inputs are CUDA tensors.
For the network we could retrieve all parameters and check if they are CUDA tensors. Something like that?

**Comment by benjamin-work** [comment]
Maybe. But we would have to test all the different routes that data can take to be certain.

**Comment by ottonemo** [comment]
The `.cuda` call is addressed in #26.

**Comment by ottonemo** [comment]
Basic functionality is guaranteed already, specific problems with `to_var` are addressed in #66.
