### ISSUE TITLE
[Bug] Binary classification on cuda fails

### ISSUE THREAD

**Issue by BenjaminBossan** [dnouri/inferno#56]
This is a similar issue as with regression and 1-dimensional target data, namely that `default_collate` unpacks the contents of the array (int64) and then the `.cuda()` call fails on int64.

It does not happen with 2-dimensional arrays, but for binary classifications, we can't use an n x 1 array, since that conflicts with `StratifiedKFold`.

**Comment by ottonemo** [comment]
Fixed in #63.
