### ISSUE TITLE
`predict` in `NeuralNet` class

### ISSUE THREAD

**Issue by benjamin-work** [dnouri/inferno#61]
`predict` will currently take the argmax of dimension 1. This is very specific, despite the `NeuralNet` class being intended for generic use cases. I see 2 solutions:

* take argmax of last dimension (thus assuming that outputs are probabilities, but not assuming a specific dimensionality)
* return the result from `forward` (thus making no assumption of what that is)

**Comment by ottonemo** [comment]
Fixed in f21d41d50fbd56cdeee27a6e78ebc92d2e68a938
