### ISSUE TITLE
Optional y in fit in general

### ISSUE THREAD

**Issue by ottonemo** [dnouri/inferno#9]
`NeuralNet.fit` should use `y=None` by default to support arbitrary data loaders.
`NeuralNetClassifier.fit` should require `y`.

**Comment by ottonemo** [comment]
The first part is done. Do we want to override `fit` in `NeuralNetClassifier` and enforce `y` @benjamin-work?

**Comment by benjamin-work** [comment]
Hmm, what do we lose if we don't?

**Comment by ottonemo** [comment]
Nothing. The user may (or may not) benefit from it because of additional error checking. 
For example, sklearn SVMs do not allow for `y=None`.

OTOH making `y` optional allows for custom data loaders that extract `y` from `X`.
So I'm leaning towards leaving `y` optional in `fit()`.

**Comment by benjamin-work** [comment]
Yes, this sounds reasonable.

The only case where I can think of where it's detrimental is when the user forgets to pass `y` to fit, at which point the error will only be noticed when `get_loss` is called. Not sure what the error message will be. Are we fine with this?

**Comment by benjamin-work** [comment]
Okay, so that means `NeuralNetRegressor` and `NeuralNetClassifier´ should not have `y=None` as default.

**Comment by ottonemo** [comment]
PR #27
